services:
  web:
    build: .
    ports:
      - "5001:5000"
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
      - celery-worker
    networks:
      - app-network

  celery-worker:
    build: .
    command: celery -A src.classifier.config.celery_config worker --loglevel=info
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:5.0.1
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge